module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "app-theme-1-text-color-1": "#FFFFFF",
        "app-theme-1-text-color-2": "#444B5A",
        "app-theme-2-text-color-1": "#FFFFFF",
        "app-theme-2-text-color-2": "#35352C",
        "app-theme-2-text-color-3": "#FFFFFF",
        "app-theme-3-text-color-1": "#1B2428",
        "app-theme-3-text-color-2": "#FFE53D",
        "app-theme-3-text-color-3": "#FFFFFF",
        "theme-white": "#FFFFFF",
        "theme-1-main-background": "#3A4764",
        "theme-2-main-background": "#E6E6E6",
        "theme-3-main-background": "#160628",
        "theme-1-toggle-background": "#232C43",
        "theme-2-toggle-background": "#D1CCCC",
        "theme-3-toggle-background": "#1D0934",
        "theme-1-screen-background": "#181F34",
        "theme-2-screen-background": "#EDEDED",
        "theme-3-screen-background": "#1D0934",
        "theme-1-key-background-1": "#637097",
        "theme-2-key-background-1": "#377F86",
        "theme-3-key-background-1": "#58077D",
        "theme-1-key-background-2": "#D03F2F",
        "theme-2-key-background-2": "#CA5502",
        "theme-3-key-background-2": "#00E0D1",
        "theme-1-key-background-3": "#EAE3DC",
        "theme-2-key-background-3": "#E5E4E1",
        "theme-3-key-background-3": "#341C4F",
        "theme-2-screen-text-color": "#35352C",
        "theme-3-screen-text-color": "#FFE53D",
      },
      fontFamily: {
        spartan: ["Spartan", "serif"],
      },
    },
  },
  plugins: [],
};
